CREATE DATABASE COFFEEANALYTICS;
USE COFFEEANALYTICS;

CREATE TABLE CLIENTE(
		IDCLIENTE						INT PRIMARY KEY AUTO_INCREMENT,
		NOME_RAZAO_SOCIAL				VARCHAR(45),
		CPF_CNPJ						VARCHAR(18) UNIQUE,
		TELEFONE_CELULAR 				VARCHAR(15) UNIQUE, 
		TELEFONE_FIXO					VARCHAR(14) UNIQUE,
		EMAIL 							VARCHAR(55) UNIQUE,
		CONSTRAINT VERIFICA_EMAIL CHECK (EMAIL LIKE '%@_%'),
        SENHA 							VARCHAR(45)
)AUTO_INCREMENT = 100;


CREATE TABLE FAZENDA(
		IDFAZENDA 					INT PRIMARY KEY AUTO_INCREMENT,
        NOME_FAZENDA				VARCHAR(50),
		CEP 						CHAR (9),
		LOGRADOURO					VARCHAR (80),
        NUMERO						INT,
		CIDADE 						VARCHAR (45),
		ESTADO 						CHAR (2),
        FKCLIENTE					INT,
        FOREIGN KEY (FKCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
)AUTO_INCREMENT = 1000;


CREATE TABLE SENSOR(
		IDSENSOR 				INT PRIMARY KEY AUTO_INCREMENT,
        LOCALIZACAO				VARCHAR(30),
		STATUS_SENSOR 			VARCHAR(10),
		CONSTRAINT VERIFICA_STATUS_SENSOR CHECK (STATUS_SENSOR = 'ativo' OR STATUS_SENSOR = 'inativo'),
		TIPO_SENSOR 			VARCHAR(5), 
		CONSTRAINT VERIFICA_TIPO_SENSOR CHECK (TIPO_SENSOR = 'DHT11'),
        FKFAZENDA 				INT,
        FOREIGN KEY (FKFAZENDA) REFERENCES FAZENDA (IDFAZENDA)
)AUTO_INCREMENT = 10;  

CREATE TABLE REGISTROS(
		IDHISTORICO 			INT PRIMARY KEY AUTO_INCREMENT,
		DATA_HORA_REGISTRO 		DATETIME,
        TEMPERATURA 			FLOAT,
		UMIDADE 				FLOAT,
        FKSENSOR				INT,
        FOREIGN KEY (FKSENSOR) REFERENCES SENSOR(IDSENSOR)
);


