CREATE DATABASE COFFEEANALYTICS;
USE COFFEEANALYTICS;


CREATE TABLE FAZENDA(
		IDFAZENDA 						INT PRIMARY KEY AUTO_INCREMENT,
		NOME_RAZAO_SOCIAL				VARCHAR(45),
        CPF_CNPJ						VARCHAR(18) UNIQUE,
        TELEFONE_CELULAR 				VARCHAR(15) UNIQUE, 
		TELEFONE_FIXO					VARCHAR(14) UNIQUE,
		EMAIL 							VARCHAR(55) UNIQUE,
        SENHA 							VARCHAR(45),
		LOGRADOURO						VARCHAR (80),
        NUMERO							INT,
		CEP 							CHAR (9),
		CIDADE 							VARCHAR (45),
		ESTADO 							CHAR (2)
        
)AUTO_INCREMENT = 1000;


CREATE TABLE SETOR(
		IDSETOR 				INT PRIMARY KEY AUTO_INCREMENT,
        NOME					VARCHAR(30),
        FKFAZENDA				INT,
        FOREIGN KEY (FKFAZENDA) REFERENCES FAZENDA(IDFAZENDA)
)AUTO_INCREMENT = 1000;  

CREATE TABLE REGISTROS(
		IDREGISTRO			INT PRIMARY KEY AUTO_INCREMENT,
        TEMPERATURA 			DOUBLE,
		UMIDADE 				DOUBLE,
		DATA_HORA_REGISTRO 		DATETIME,
        FKSETOR			INT,
        FOREIGN KEY (FKSETOR) REFERENCES SETOR(IDSETOR)
);





